### PR TITLE
CSS, login, topbar, recognitions, reporting (from /lily), columnar homepage

### PR DESCRIPTION
**Pull request by wmchristopher**

### CODE REVIEW

**Review by wmchristopher — COMMENTED** [review]
I made a few visual changes to the pages I found and could display, in accordance with my Trello task

**Comment by wmchristopher** [comment]
alright. I believe it is ready

**Comment by wmchristopher** [comment]
that did not do what I thought it did

**Review by cunbidun — DISMISSED** [review]

**Comment by wmchristopher** [comment]
okay: I think this is ready now. a _ton_ of the CSS was disrupted since I last set it up, so I fixed it and simplified the directories. I plan to do more along these lines soon. but now you should see the beautiful typefaces I installed instead of the ugly system default. I also plan to make similar changes for the profile page once I get access

**Comment by wmchristopher** [comment]
looking to add an accent color here, maybe some kind of green, but waiting for API sync so I can balance it with _real backend information!_

**Comment by wmchristopher** [comment]
I believe my front-end tasks for the week are done.  I had told some folk on the front-end I would oversee their merges.  I have done so with Lily’s (into mine).  I have not yet done so for anyone’s else, in apprehension of our weekly merges.

**Review by yunjoey — APPROVED** [review]

**Review by k2nt — APPROVED** [review]

**Pull request merged**
